### ISSUE TITLE
failure with weird character at beginning of file

### ISSUE THREAD

**Issue by jkone27** [cgkineo/babel-plugin-transform-amd-to-es6#2]
```
| ��/// <reference path="bootstrap.js" />
```

couldnt reckognize exactly if there is any issue about any specific chars

<img width="601" alt="image" src="https://user-images.githubusercontent.com/10419217/180217759-0b0cf938-d807-4cf1-a3aa-7594f7512e49.png">

**Comment by oliverfoster** [comment]
that's almost certainly not added by this code, are you using utf-8 files?
